platform :ios, '16.0'

use_frameworks!
workspace 'Modularization'

target 'App' do
  
end

target 'Common' do

  project '../Common/Common'

end

target 'Cart' do

  project '../Cart/Cart'

end

target 'Product' do

  project '../Product/Product'

end